import os
import subprocess
from pathlib import Path
from typing import Optional, Tuple

from app.config import CACHE_PATH, RESOURCE_PATH
from app.core.subtitle_processor.effect_manager import EffectManager

from .logger import setup_logger
from .ass_auto_wrap import auto_wrap_ass_file
from .video_utils import get_video_info

logger = setup_logger("subtitle_preview")

SCRIPT_INFO_TEMPLATE = """[Script Info]
; Script generated by VideoSubtitleEditor
; https://github.com/WEIFENG2333
ScriptType: v4.00+
PlayResX: {video_width}
PlayResY: {video_height}


{style_str}

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
{dialogue}
"""

ASS_TEMP_FILENAME = CACHE_PATH / "preview.ass"  # 预览的临时 ASS 文件路径
PREVIEW_IMAGE_FILENAME = CACHE_PATH / "preview.png"  # 预览的图片路径
PREVIEW_VIDEO_FILENAME = CACHE_PATH / "preview_effect.mp4"
DEFAULT_BG_PATH = RESOURCE_PATH / "assets" / "default_bg.png"


def run_subprocess(command: list):
    """运行子进程命令，并处理异常"""
    try:
        result = subprocess.run(
            command,
            check=True,
            capture_output=True,
            creationflags=subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0,
        )
        return result
    except subprocess.CalledProcessError as e:
        stderr = (
            e.stderr.decode("utf-8", errors="ignore")
            if isinstance(e.stderr, (bytes, bytearray))
            else str(e.stderr)
        )
        logger.error(f"Subprocess error: {stderr}")
        raise RuntimeError(f"FFmpeg command failed: {stderr}") from e


def generate_ass_file(
    style_str: str,
    preview_text: Tuple[str, Optional[str]],
    video_width: int = 1280,
    video_height: int = 720,
    effect_type: str = "none",
    effect_duration_ms: int = 300,
    effect_intensity: float = 1.0,
    rainbow_end_color: str = "#0000FF",
    motion_direction: str = "up",
    motion_amplitude: float = 1.0,
    motion_easing: str = "ease_out",
    motion_jitter: float = 0.0,
    motion_blur_strength: float = 0.0,
    karaoke_mode: bool = False,
    karaoke_window_ms: int = 1200,
    auto_contrast: bool = False,
    anti_flicker: bool = False,
    gradient_mode: str = "off",
    gradient_color_1: str = "#FFFFFF",
    gradient_color_2: str = "#66CCFF",
    safe_area_enabled: bool = True,
    safe_margin_x: int = 8,
    safe_margin_y: int = 10,
    speaker_color_mode: str = "off",
) -> str:
    """生成临时 ASS 文件"""
    original_text, translate_text = preview_text

    def _extract_style_position(styles_text: str, style_name: str) -> tuple[int, int, int, int]:
        """Возвращает (alignment, margin_l, margin_r, margin_v) для стиля."""
        if not styles_text:
            return 2, 10, 10, 10
        import re

        m = re.search(rf"^Style:\s*{re.escape(style_name)}\s*,\s*(.+)$", styles_text, re.MULTILINE)
        if not m:
            return 2, 10, 10, 10
        parts = [p.strip() for p in m.group(1).split(",")]
        # indexes after Name field in ASS style line:
        # Alignment=18, MarginL=19, MarginR=20, MarginV=21
        try:
            alignment = int(float(parts[17]))
            margin_l = int(float(parts[18]))
            margin_r = int(float(parts[19]))
            margin_v = int(float(parts[20]))
            return alignment, margin_l, margin_r, margin_v
        except (IndexError, ValueError):
            return 2, 10, 10, 10

    def _anchor_from_style(alignment: int, margin_l: int, margin_r: int, margin_v: int) -> tuple[int, int]:
        # ASS numpad alignment: 1..3 bottom, 4..6 middle, 7..9 top
        col = ((alignment - 1) % 3) + 1
        row = ((alignment - 1) // 3) + 1

        if col == 1:
            x = margin_l
        elif col == 2:
            x = video_width // 2
        else:
            x = video_width - margin_r

        if row == 1:
            y = video_height - margin_v
        elif row == 2:
            y = video_height // 2
        else:
            y = margin_v

        return int(max(0, min(video_width, x))), int(max(0, min(video_height, y)))

    def _extract_style_blur(styles_text: str, style_name: str) -> float:
        if not styles_text:
            return 0.0
        import re

        m = re.search(rf";VC_BLUR:{re.escape(style_name)}=([0-9.]+)", styles_text)
        if not m:
            return 0.0
        try:
            return float(m.group(1))
        except ValueError:
            return 0.0

    default_blur = _extract_style_blur(style_str, "Default")
    secondary_blur = _extract_style_blur(style_str, "Secondary")
    default_anchor = _anchor_from_style(*_extract_style_position(style_str, "Default"))
    secondary_anchor = _anchor_from_style(*_extract_style_position(style_str, "Secondary"))

    preview_start_ms = 0
    preview_end_ms = 2000
    original_text = EffectManager.apply_ass_effect(
        original_text,
        effect_type=effect_type,
        start_ms=preview_start_ms,
        end_ms=preview_end_ms,
        effect_duration_ms=effect_duration_ms,
        effect_intensity=effect_intensity,
        rainbow_end_color=rainbow_end_color,
        index=0,
        motion_direction=motion_direction,
        motion_amplitude=motion_amplitude,
        motion_easing=motion_easing,
        motion_jitter=motion_jitter,
        motion_blur_strength=motion_blur_strength,
        play_res_x=video_width,
        play_res_y=video_height,
        karaoke_mode=karaoke_mode,
        karaoke_window_ms=karaoke_window_ms,
        auto_contrast=auto_contrast,
        anti_flicker=anti_flicker,
        gradient_mode=gradient_mode,
        gradient_color_1=gradient_color_1,
        gradient_color_2=gradient_color_2,
        safe_area_enabled=safe_area_enabled,
        safe_margin_x=safe_margin_x,
        safe_margin_y=safe_margin_y,
        speaker_color_mode=speaker_color_mode,
        use_word_timestamps=False,
        anchor_x=default_anchor[0],
        anchor_y=default_anchor[1],
    )
    translated_text = EffectManager.apply_ass_effect(
        translate_text,
        effect_type=effect_type,
        start_ms=preview_start_ms,
        end_ms=preview_end_ms,
        effect_duration_ms=effect_duration_ms,
        effect_intensity=effect_intensity,
        rainbow_end_color=rainbow_end_color,
        index=1,
        motion_direction=motion_direction,
        motion_amplitude=motion_amplitude,
        motion_easing=motion_easing,
        motion_jitter=motion_jitter,
        motion_blur_strength=motion_blur_strength,
        play_res_x=video_width,
        play_res_y=video_height,
        karaoke_mode=karaoke_mode,
        karaoke_window_ms=karaoke_window_ms,
        auto_contrast=auto_contrast,
        anti_flicker=anti_flicker,
        gradient_mode=gradient_mode,
        gradient_color_1=gradient_color_1,
        gradient_color_2=gradient_color_2,
        safe_area_enabled=safe_area_enabled,
        safe_margin_x=safe_margin_x,
        safe_margin_y=safe_margin_y,
        speaker_color_mode=speaker_color_mode,
        use_word_timestamps=False,
        anchor_x=secondary_anchor[0],
        anchor_y=secondary_anchor[1],
    )

    if original_text and default_blur > 0:
        original_text = f"{{\\blur{default_blur}}}{original_text}"
    if translated_text and secondary_blur > 0:
        translated_text = f"{{\\blur{secondary_blur}}}{translated_text}"

    dialogue = (
        [
            f"Dialogue: 0,0:00:00.00,0:00:02.00,Secondary,,0,0,0,,{translated_text}",
            f"Dialogue: 0,0:00:00.00,0:00:02.00,Default,,0,0,0,,{original_text}",
        ]
        if translate_text
        else [f"Dialogue: 0,0:00:00.00,0:00:02.00,Default,,0,0,0,,{original_text}"]
    )

    ass_content = SCRIPT_INFO_TEMPLATE.format(
        style_str=style_str,
        dialogue=os.linesep.join(dialogue),
        video_width=video_width,
        video_height=video_height,
    )
    ASS_TEMP_FILENAME.parent.mkdir(parents=True, exist_ok=True)
    ASS_TEMP_FILENAME.write_text(ass_content, encoding="utf-8")
    return str(ASS_TEMP_FILENAME)


def ensure_background(bg_path: Path) -> Path:
    """确保背景图片存在，若不存在则创建默认黑色背景"""
    if not bg_path.is_file() or not bg_path.exists():
        if not Path(DEFAULT_BG_PATH).exists():
            DEFAULT_BG_PATH.parent.mkdir(parents=True, exist_ok=True)
            run_subprocess(
                [
                    "ffmpeg",
                    "-f",
                    "lavfi",
                    "-i",
                    "color=c=black:s=1920x1080",
                    "-frames:v",
                    "1",
                    str(DEFAULT_BG_PATH),
                ]
            )
        return Path(DEFAULT_BG_PATH)
    return bg_path


def generate_preview(
    style_str: str,
    preview_text: Tuple[str, Optional[str]],
    bg_path: str,
    width: int,
    height: int,
    effect_type: str = "none",
    effect_duration_ms: int = 300,
    effect_intensity: float = 1.0,
    rainbow_end_color: str = "#0000FF",
    motion_direction: str = "up",
    motion_amplitude: float = 1.0,
    motion_easing: str = "ease_out",
    motion_jitter: float = 0.0,
    motion_blur_strength: float = 0.0,
    karaoke_mode: bool = False,
    karaoke_window_ms: int = 1200,
    auto_contrast: bool = False,
    anti_flicker: bool = False,
    gradient_mode: str = "off",
    gradient_color_1: str = "#FFFFFF",
    gradient_color_2: str = "#66CCFF",
    safe_area_enabled: bool = True,
    safe_margin_x: int = 8,
    safe_margin_y: int = 10,
    speaker_color_mode: str = "off",
    preview_time_sec: float = 0.0,
    frame_token: Optional[str] = None,
) -> str:
    """生成预览图片"""

    ass_file = generate_ass_file(
        style_str,
        preview_text,
        width,
        height,
        effect_type,
        effect_duration_ms,
        effect_intensity,
        rainbow_end_color,
        motion_direction,
        motion_amplitude,
        motion_easing,
        motion_jitter,
        motion_blur_strength,
        karaoke_mode,
        karaoke_window_ms,
        auto_contrast,
        anti_flicker,
        gradient_mode,
        gradient_color_1,
        gradient_color_2,
        safe_area_enabled,
        safe_margin_x,
        safe_margin_y,
        speaker_color_mode,
    )
    ass_file = auto_wrap_ass_file(ass_file)
    bg_path = ensure_background(Path(bg_path))

    output_path = (
        CACHE_PATH / f"preview_{frame_token}.png"
        if frame_token
        else PREVIEW_IMAGE_FILENAME
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)

    ass_file_processed = ass_file.replace("\\", "/").replace(":", r"\\:")
    preview_time_sec = max(0.0, float(preview_time_sec))
    loop_duration = max(1.5, preview_time_sec + 0.2)

    cmd = [
        "ffmpeg",
        "-y",
        "-loop",
        "1",
        "-t",
        str(loop_duration),
        "-i",
        str(bg_path),
        "-ss",
        str(preview_time_sec),
        "-vf",
        f"ass={ass_file_processed}",
        "-frames:v",
        "1",
        str(output_path),
    ]
    run_subprocess(cmd)
    if not output_path.exists():
        raise FileNotFoundError(f"Preview image not generated: {output_path}")
    return str(output_path)


def generate_preview_video(
    style_str: str,
    preview_text: Tuple[str, Optional[str]],
    bg_path: str,
    width: int,
    height: int,
    effect_type: str = "none",
    effect_duration_ms: int = 300,
    effect_intensity: float = 1.0,
    rainbow_end_color: str = "#0000FF",
    motion_direction: str = "up",
    motion_amplitude: float = 1.0,
    motion_easing: str = "ease_out",
    motion_jitter: float = 0.0,
    motion_blur_strength: float = 0.0,
    karaoke_mode: bool = False,
    karaoke_window_ms: int = 1200,
    auto_contrast: bool = False,
    anti_flicker: bool = False,
    gradient_mode: str = "off",
    gradient_color_1: str = "#FFFFFF",
    gradient_color_2: str = "#66CCFF",
    safe_area_enabled: bool = True,
    safe_margin_x: int = 8,
    safe_margin_y: int = 10,
    speaker_color_mode: str = "off",
    duration_sec: float = 2.0,
) -> str:
    """Генерирует короткое видео предпросмотра с анимацией эффекта."""

    ass_file = generate_ass_file(
        style_str,
        preview_text,
        width,
        height,
        effect_type,
        effect_duration_ms,
        effect_intensity,
        rainbow_end_color,
        motion_direction,
        motion_amplitude,
        motion_easing,
        motion_jitter,
        motion_blur_strength,
        karaoke_mode,
        karaoke_window_ms,
        auto_contrast,
        anti_flicker,
        gradient_mode,
        gradient_color_1,
        gradient_color_2,
        safe_area_enabled,
        safe_margin_x,
        safe_margin_y,
        speaker_color_mode,
    )
    ass_file = auto_wrap_ass_file(ass_file)
    bg_path = ensure_background(Path(bg_path))

    output_path = PREVIEW_VIDEO_FILENAME
    output_path.parent.mkdir(parents=True, exist_ok=True)

    ass_file_processed = ass_file.replace("\\", "/").replace(":", r"\\:")
    cmd = [
        "ffmpeg",
        "-y",
        "-loop",
        "1",
        "-i",
        str(bg_path),
        "-vf",
        f"ass={ass_file_processed}",
        "-t",
        str(duration_sec),
        "-r",
        "30",
        "-pix_fmt",
        "yuv420p",
        str(output_path),
    ]
    run_subprocess(cmd)
    if not output_path.exists():
        raise FileNotFoundError(f"Preview video not generated: {output_path}")
    return str(output_path)


if __name__ == "__main__":
    style_str = """[V4+ Styles]
Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,StrikeOut,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
Style: Default,微软雅黑,70,&H00eb7f33,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,2.0,0,1,2.0,0,2,10,10,10,1
Style: Translate,微软雅黑,40,&H00eff0f3,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0.0,0,1,1.0,0,2,10,10,10,1
"""
    bg_path = r"C:\Users\weifeng\Pictures\Animated_character_spraying_liquid.jpg"
    preview_text = ("Hello, world!", "你好，世界！")
    print(generate_preview(style_str, preview_text, bg_path))
